"""Public record schemas for CLI and documentation."""

from __future__ import annotations

from dataclasses import MISSING, fields
from types import UnionType
from typing import Any, Union, get_args, get_origin

from .models import CatalogRecord, PriceRecord, PriceTarget

SCHEMA_MODELS = {
    "catalog": CatalogRecord,
    "price": PriceRecord,
    "target": PriceTarget,
}

DESCRIPTIONS = {
    "channel": "Retail Scrapers channel ID.",
    "country": "ISO-like market code used by the adapter.",
    "sku": "Retailer SKU or stable product identifier.",
    "brand": "Retailer-provided brand name.",
    "title": "Retailer-provided product title.",
    "url": "Canonical or product detail URL.",
    "price": "Native current price when available.",
    "currency": "Retailer-native currency code.",
    "availability": "Coarse availability status when available.",
    "model": "Retailer or manufacturer model text when available.",
    "model_year": "Model year when the source exposes it.",
    "size_inch": "Screen or product size in inches when available.",
    "scraped_at": "UTC timestamp generated by the scraper.",
    "metadata": "Adapter-specific public auxiliary fields.",
    "id": "User-provided target identifier for price extraction.",
    "status": "Price extraction status, usually success or failed.",
}


def record_schema(name: str) -> dict[str, Any]:
    key = name.strip().lower()
    try:
        model = SCHEMA_MODELS[key]
    except KeyError as exc:
        raise ValueError(
            f"unknown schema {name!r}; choose one of: {', '.join(SCHEMA_MODELS)}"
        ) from exc

    properties = {}
    required = []
    for field in fields(model):
        properties[field.name] = {
            "type": _type_name(field.type),
            "description": DESCRIPTIONS.get(field.name, ""),
        }
        if field.default is MISSING and field.default_factory is MISSING:
            required.append(field.name)
    return {
        "name": key,
        "record": model.__name__,
        "required": required,
        "properties": properties,
    }


def all_schemas() -> dict[str, dict[str, Any]]:
    return {name: record_schema(name) for name in SCHEMA_MODELS}


def schema_markdown(name: str = "all") -> str:
    selected = all_schemas() if name == "all" else {name: record_schema(name)}
    sections = []
    for schema in selected.values():
        lines = [
            f"## {schema['record']}",
            "",
            "| Field | Type | Required | Description |",
            "|---|---|---:|---|",
        ]
        required = set(schema["required"])
        for field_name, spec in schema["properties"].items():
            lines.append(
                "| "
                + " | ".join(
                    [
                        f"`{field_name}`",
                        f"`{spec['type']}`",
                        "Yes" if field_name in required else "No",
                        _escape_markdown(str(spec["description"])),
                    ]
                )
                + " |"
            )
        sections.append("\n".join(lines))
    return "\n\n".join(sections)


def _type_name(annotation: Any) -> str:
    if isinstance(annotation, str):
        return annotation
    origin = get_origin(annotation)
    args = get_args(annotation)
    if origin in (UnionType, Union):
        return " | ".join(_type_name(arg) for arg in args)
    if origin is dict:
        key, value = args or ("Any", "Any")
        return f"dict[{_type_name(key)}, {_type_name(value)}]"
    if hasattr(annotation, "__name__"):
        return str(annotation.__name__)
    return str(annotation).replace("typing.", "")


def _escape_markdown(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")
